services:
  # Frontend Service
  - type: web
    name: fintan-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build:frontend
    startCommand: npm run start:frontend
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: fintan-backend
          property: host
      - key: VITE_DAILY_DOMAIN
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: VITE_DEFAULT_PROVIDER_ID
        sync: false

  # Backend Service
  - type: web
    name: fintan-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: DAILY_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  - name: fintan-db
    databaseName: fintan
    user: fintan_user
    plan: free
